from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from .io import write_text


def generate_release_notes(version: str, output_dir: str | Path = "releases") -> Path:
    generated = datetime.now(timezone.utc).isoformat()
    content = f"""---
title: "EAODS {version} Release Notes"
version: "{version}"
generated: "{generated}"
classification: "Internal / Portfolio / Commercialization Candidate"
---

# EAODS {version} Release Notes

## Summary

This release was generated by the EAODS runtime scaffold.

## Included Changes

- Updated documentation artifacts
- Updated workflow state where applicable
- Updated QA/evaluation support

## Required Review

- Confirm no secrets are present.
- Confirm YAML front matter remains valid.
- Confirm human approval gates are included where required.
- Confirm release version and scope.

## Release Decision

- [ ] Approved
- [ ] Approved with changes
- [ ] Rejected
"""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{version}_release_notes.md"
    write_text(path, content)
    return path
